# Erste Versuche mit Tensorflow 

In [3]:
import tensorflow as tf
print("Tensorflow Version:", tf.__version__)

Tensorflow Version: 2.14.0


## Datenaufbereitung

Minst dataset vorbereiten http://yann.lecun.com/exdb/mnist/
Bilder enthalten habdgezeichnete Zahlen
Die Pixel der Bilder haben werte von 0 - 255, weshalb daten auf 0-1 umgerechnet werden



In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test)=mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 2s 0us/step


## Keras Sequential modell erstellen
Sequential  ist ein Neural Network bei dem jede layer exakt einen input und einen Output hat

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.35304904,  0.38142538,  0.42169195,  0.12768441, -0.12804517,
         0.41636658, -0.0055618 , -0.39404744,  0.12753075,  0.54875493]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.05974108, 0.12452348, 0.12963994, 0.09661686, 0.0748154 ,
        0.12895139, 0.08456387, 0.05734132, 0.09660202, 0.14720467]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.0483198

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 14s 6ms/step - loss: 0.4012 - accuracy: 0.8847
Epoch 2/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3693 - accuracy: 0.8984
Epoch 3/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3862 - accuracy: 0.8955
Epoch 4/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.4046 - accuracy: 0.8925
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.4169 - accuracy: 0.8906


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - loss: 0.3656 - accuracy: 0.9063 - 2s/epoch - 7ms/step


[0.36556658148765564, 0.9063000082969666]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.79688260e-03, 2.26771011e-08, 1.24411546e-01, 4.95023727e-02,
        1.25808816e-03, 3.05663757e-02, 4.63867764e-07, 7.85788000e-01,
        2.64708162e-03, 4.02921578e-03],
       [4.59505427e-05, 7.36306390e-07, 9.49869275e-01, 3.02962996e-02,
        4.98678503e-07, 1.27431210e-02, 7.97441025e-05, 5.81585058e-10,
        6.96362136e-03, 8.25755649e-07],
       [6.80806011e-07, 3.12579721e-01, 1.86952620e-05, 7.05249386e-06,
        4.87616330e-01, 3.10580945e-05, 2.82466819e-04, 1.84557766e-01,
        1.08987209e-04, 1.47971483e-02],
       [4.82635707e-01, 1.32386810e-06, 9.90634508e-05, 3.45341078e-07,
        2.63713658e-01, 2.37210683e-04, 9.72453039e-03, 1.63988560e-01,
        6.12111899e-06, 7.95934647e-02],
       [3.08329362e-10, 1.49076636e-11, 1.85132715e-10, 3.88109073e-10,
        9.99615073e-01, 1.85246037e-07, 1.07001966e-07, 3.11760751e-08,
        1.67359584e-08, 3.84589337e-04]], dtype=float32)>